### Variables
@baseURL = http://localhost:4000
@authToken ={{$dotenv TEST_AUTH_TOKEN}}

### 1. Agregar un amigo
POST {{baseURL}}/friends
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "friendId": "user_30LK98iRP05YveRNM8FKODZ3BSS"
}

### 2. Aceptar solicitud de amistad
PATCH {{baseURL}}/friends/f251acdc-52d7-4ab4-b8e9-899d74275bf4
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "status": "rejected"
}

### 3. Rechazar solicitud de amistad
PATCH {{baseURL}}/friends/f251acdc-52d7-4ab4-b8e9-899d74275bf4
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "status": "rejected"
}

### 4. Bloquear usuario
PATCH {{baseURL}}/friends/b7008831-a52f-4384-88ac-55b5ae026b87
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "status": "blocked"
}

### 5. Obtener lista de amigos
GET {{baseURL}}/friends
Authorization: Bearer {{authToken}}

### 6. Obtener solicitudes pendientes
GET {{baseURL}}/friends/requests
Authorization: Bearer {{authToken}}

### 7. Eliminar amigo
DELETE {{baseURL}}/friends/b7008831-a52f-4384-88ac-55b5ae026b87
Authorization: Bearer {{authToken}}
