### Insertar un nuevo game (requiere token JWT en Authorization)
POST http://localhost:4000/games
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyXzMwUUhmaE94aDhGSHZrbTJIenhlWXVBVEYxVCIsImVtYWlsIjoibHVjaWFuby56YXBhdGEzMTRAZ21haWwuY29tIiwiZnVsbE5hbWUiOiJsdWNpYW5vIHphcGF0YSIsInJvbGVzIjpbXSwiaWF0IjoxNzUzNTg4MzI5LCJleHAiOjE3NTQxOTMxMjl9.OGQZHCCQoTAsgAdBZo7v_IBh2_03ddoIc7r9P2HfdzI
Content-Type: application/json

{
  "fieldId": "0c206827-88b9-491d-be10-e73ae5998955",
  "gameType": 5,
  "gameLevel": 1,
  "startTime": "2025-08-01T18:00:00.000Z",
  "endTime": "2025-08-01T19:00:00.000Z",
  "totalSpots": 10,
  "availableSpots": 10,
  "pricePerPlayer": 100.00,
  "status": "open"
}

### Obtener todos los games
GET http://localhost:4000/games
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyXzMwUUhmaE94aDhGSHZrbTJIenhlWXVBVEYxVCIsImVtYWlsIjoibHVjaWFuby56YXBhdGEzMTRAZ21haWwuY29tIiwiZnVsbE5hbWUiOiJsdWNpYW5vIHphcGF0YSIsInJvbGVzIjpbXSwiaWF0IjoxNzUzNTg4MzI5LCJleHAiOjE3NTQxOTMxMjl9.OGQZHCCQoTAsgAdBZo7v_IBh2_03ddoIc7r9P2HfdzI

### Obtener un game por id
GET http://localhost:4000/games/c803a552-cd47-4f1a-90a1-0d5a026b6c38
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyXzMwUUhmaE94aDhGSHZrbTJIenhlWXVBVEYxVCIsImVtYWlsIjoibHVjaWFuby56YXBhdGEzMTRAZ21haWwuY29tIiwiZnVsbE5hbWUiOiJsdWNpYW5vIHphcGF0YSIsInJvbGVzIjpbXSwiaWF0IjoxNzUzNTg4MzI5LCJleHAiOjE3NTQxOTMxMjl9.OGQZHCCQoTAsgAdBZo7v_IBh2_03ddoIc7r9P2HfdzI

### Actualizar un game
PATCH http://localhost:4000/games/c803a552-cd47-4f1a-90a1-0d5a026b6c38
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyXzMwUUhmaE94aDhGSHZrbTJIenhlWXVBVEYxVCIsImVtYWlsIjoibHVjaWFuby56YXBhdGEzMTRAZ21haWwuY29tIiwiZnVsbE5hbWUiOiJsdWNpYW5vIHphcGF0YSIsInJvbGVzIjpbXSwiaWF0IjoxNzUzNTg4MzI5LCJleHAiOjE3NTQxOTMxMjl9.OGQZHCCQoTAsgAdBZo7v_IBh2_03ddoIc7r9P2HfdzI
Content-Type: application/json

{
  "status": "full"
}

### Eliminar un game
DELETE http://localhost:4000/games/c803a552-cd47-4f1a-90a1-0d5a026b6c38
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyXzMwUUhmaE94aDhGSHZrbTJIenhlWXVBVEYxVCIsImVtYWlsIjoibHVjaWFuby56YXBhdGEzMTRAZ21haWwuY29tIiwiZnVsbE5hbWUiOiJsdWNpYW5vIHphcGF0YSIsInJvbGVzIjpbXSwiaWF0IjoxNzUzNTg4MzI5LCJleHAiOjE3NTQxOTMxMjl9.OGQZHCCQoTAsgAdBZo7v_IBh2_03ddoIc7r9P2HfdzI
