@authToken = {{$dotenv TEST_AUTH_TOKEN}}

### Insertar un nuevo game (requiere token JWT en Authorization)
POST http://localhost:4000/games
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "fieldId": "c25f9245-cfed-4c36-96d3-5317f19de04e",
  "gameType": 5,
  "gameLevel": 1,
  "startTime": "2025-08-01T18:00:00.000Z",
  "endTime": "2025-08-01T19:00:00.000Z",
  "totalSpots": 10,
  "availableSpots": 10,
  "pricePerPlayer": 100.00,
  "status": "open"
}

### Obtener todos los games
GET http://localhost:4000/games
Authorization: Bearer {{authToken}}

### Obtener un game por id
GET http://localhost:4000/games/c803a552-cd47-4f1a-90a1-0d5a026b6c38
Authorization: Bearer {{authToken}}

### Actualizar un game
PATCH http://localhost:4000/games/43c27a2b-5872-4dac-a03c-9491169ebcab
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "status": "open"
}

### Eliminar un game
DELETE http://localhost:4000/games/66fa4e2d-a4bd-450d-85c1-7426a3a1f4a8
Authorization: Bearer {{authToken}}

### Obtener juegos cercanos
GET http://localhost:4000/games/nearby?latitude=-31.8273833&longitude=-60.5213283&radius=10
Authorization: Bearer {{authToken}}
