name: Deploy to EC2

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ closed ]
    branches: [ "main" ]

jobs:
  deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    concurrency: deploy-main

    steps:
      - name: Check required secrets
        run: |
          [ -n "${{ secrets.EC2_HOST }}" ] || { echo "Missing secret: EC2_HOST"; exit 1; }
          [ -n "${{ secrets.EC2_USER }}" ] || { echo "Missing secret: EC2_USER"; exit 1; }
          [ -n "${{ secrets.EC2_SSH_KEY }}" ] || { echo "Missing secret: EC2_SSH_KEY"; exit 1; }
          # EC2_PORT es opcional: default 22
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host:     ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key:      ${{ secrets.EC2_SSH_KEY }}
          port:     ${{ secrets.EC2_PORT || 22 }}
          script: |
            cd /home/ec2-user/app-backend
            bash ./deploy.sh
